# Generated by Django 4.1.7 on 2023-03-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(choices=[('employee', 'employee'), ('manager', 'manager')], default='EMPLOYEE', max_length=20)),
                ('manager', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=20)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
    ]
